package com.sinchana.credit_card_management_service.mapper;

import com.sinchana.credit_card_management_service.dto.request.CardApplicationRequestDTO;
import com.sinchana.credit_card_management_service.dto.response.CardApplicationResponseDTO;
import com.sinchana.credit_card_management_service.entity.CardApplication;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface CardApplicationMapper {

    @Mapping(target = "id", ignore = true) // generated by DB
    @Mapping(target = "applicationDate", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "reviewedBy", ignore = true)
    @Mapping(target = "reviewDate", ignore = true)
    @Mapping(target = "user", ignore = true) // set in service layer
    CardApplication toEntity(CardApplicationRequestDTO dto);

    @Mapping(source = "user.id", target = "userId")
    @Mapping(source = "reviewedBy.id", target = "reviewedBy")
    @Mapping(target = "requestedLimit", ignore = true) // no such field in entity
    CardApplicationResponseDTO toResponseDTO(CardApplication entity);
}
