package com.sinchana.credit_card_management_service.mapper;

import com.sinchana.credit_card_management_service.dto.request.CardRequestDTO;
import com.sinchana.credit_card_management_service.dto.response.CardResponseDTO;
import com.sinchana.credit_card_management_service.entity.Card;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring")
public interface CardMapper {

    CardMapper INSTANCE = Mappers.getMapper(CardMapper.class);

    // Request DTO → Entity
    @Mapping(target = "id", ignore = true)          // DB generated
    @Mapping(target = "cardNumber", ignore = true)  // generated by system
    @Mapping(target = "status", ignore = true)      // default ACTIVE/PENDING
    @Mapping(target = "availableLimit", ignore = true) // initially equals creditLimit
    Card toEntity(CardRequestDTO dto);

    // Entity → Response DTO
    CardResponseDTO toResponseDTO(Card card);
}
