package com.sinchana.credit_card_management_service.mapper;

import com.sinchana.credit_card_management_service.dto.request.UserProfileRequestDTO;
import com.sinchana.credit_card_management_service.dto.response.UserProfileResponseDTO;
import com.sinchana.credit_card_management_service.entity.UserProfile;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring")
public interface UserProfileMapper {

    UserProfileMapper INSTANCE = Mappers.getMapper(UserProfileMapper.class);

    // Request DTO → Entity
    @Mapping(target = "id", ignore = true)  // ID is generated by DB
    UserProfile toEntity(UserProfileRequestDTO dto);

    // Entity → Response DTO
    UserProfileResponseDTO toResponseDTO(UserProfile userProfile);
}
